WatchEventStoreUri: "mondodb://<MONGO-SERVER>:27017"
WatchDomainName: "Fabrica.One.Production"

OneRoot: "/home/<USER>/fabrica-one-root"

#UseInstanceMetadata: true

#AppConfigCheckIntervalSecs: 30
#AppConfigPlanSourceApplication: ""
#AppConfigPlanSourceConfiguration: ""
#AppConfigPlanSourceEnvironment: ""

RepositoryBucketName: "<REPO-NAME>-appliance-repository"