// ReSharper disable CommentTypo
// ReSharper disable IdentifierTypo
// ReSharper disable UnusedMember.Global

/**************************************************************
AUTO GENERATED BY Fabrica Application Studio
DO NOT MODIFY THIS FILE
**************************************************************/

using Fabrica.Models.Support;

namespace Fabrica.Work.Endpoints
{

    public class WorkTopicDelta : BaseDelta
    {

        public  string? Environment { get; set; }
        public  string? TenantUid { get; set; }
        public  string? Topic { get; set; }
        public  string? Description { get; set; }
        public  bool? Synchronous { get; set; }
        public  string? ClientName { get; set; }
        public  string? Path { get; set; }
        public  string? FullUrl { get; set; }


	}		

	
}
