RunningOnEc2: true
RegionName: ""
ProfileName: ""
AwsSecretsKeyId: ""
ApplicationDiscriminator: "Fabrica-Proxy"
DataProtectionParameterName: ""

UseSession: true
RedisConnectionStr: "localhost"

AllowAnyIp: true

