RegionName: us-east-2
Profile: kampilan
RunningOnEC2: false

OneRoot: "e:/fabrica-one"

UnderOrchestration: true

UseInstanceMetatdata: true
AppConfigPlanSourceApplication: ""
AppConfigPlanSourceEnvironment: ""
AppConfigPlanSourceConfiguration: ""

RepositoryBucketName: "pondhawk-appliance-repository"