WatchEventStoreUri: "mondodb://<MONGO-SERVER>:27017"
WatchDomainName: "Fabrica.One.Production"

OneRoot: "/home/<USER>/fabrica-one-root"

#UnderOrchestration: true
#UseExternalPlanSource: true
#ProduceEmptyPlans: true