# Amazon credential related settings
Profile: kampilan
RegionName: us-east-2
RunningOnEC2: false


OriginDbConnectionStr: "Server=10.78.142.10; Database=fabrica_identity;Uid=appserver;Pwd=rHUAZWHe9rDrRedL8hcT;UseAffectedRows=false;AllowUserVariables=true"


MissionName: Local-Test
ApplianceName: fabrica-identity
ApplianceBuild: "Local"
Environment: Development
ListeningPort: 8888
WatchDomainName: Fabrica.System.Development
WatchEventStoreUri: "mongodb://watch:w1FfV1qfZQJKTFv0zpme@10.78.142.10:27017"
